---
title: "R Notebook"
output: html_notebook
---

# `DSAIC HACKATHON 2024`
# Fraud Detection in Electricity and Gas Consumption Challenge
`This notebook serves as a starter notebook and prepared by DeKUTR club`

## Introduction
The Tunisian Company of Electricity and Gas (STEG) is a public entity responsible for providing electricity and gas services across Tunisia. The company has faced significant financial losses, estimated at 200 million Tunisian Dinars, due to fraudulent manipulations of consumer meters. This project aims to leverage clients' billing history to develop a solution that detects and identifies customers engaged in fraudulent activities. By implementing this system, STEG seeks to enhance revenue generation and mitigate losses caused by such fraudulent behaviors.

## Data
The data provided by STEG is composed of two files. The first one is comprised of client data and the second one contains billing history from 2005 to 2019.

There are 2 .zip files for download, train.zip, and test.zip and a SampleSubmission.csv. In each .zip file you will find a client and invoice file.

The data can download in this link:
https://drive.google.com/drive/folders/1npnp3a_-dTwGmXKffsAmybV6tDP4Gob6

## Features
Variable definitions

Client:

- Client_id: Unique id for client

- District: District where the client is

- Client_catg: Category client belongs to

- Region: Area where the client is

- Creation_date: Date client joined

- Target: fraud:1 , not fraud: 0

Invoice data

- Client_id: Unique id for the client

- Invoice_date: Date of the invoice

- Tarif_type: Type of tax

- Counter_number:

- Counter_statue: takes up to 5 values such as working fine, not working, on hold statue, ect

- Counter_code:

- Reading_remarque: notes that the STEG agent takes during his visit to the client (e.g: If the counter shows something wrong, the agent gives a bad score)

- Counter_coefficient: An additional coefficient to be added when standard consumption is exceeded

- Consommation_level_1: Consumption_level_1

- Consommation_level_2: Consumption_level_2

- Consommation_level_3: Consumption_level_3

- Consommation_level_4: Consumption_level_4

- Old_index: Old index

- New_index: New index

- Months_number: Month number

- Counter_type: Type of counter